### ISSUE TITLE
Status of aide_design on pip

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/aguaclara#85]
I notice that the aide_design being used in pip has a different file structure than the most updated version, which is branch 'filter_design' as far as I know. 

Is there a plan to push this newest version to pip soon?

This comes up as I try to design an LFOM and get the following error, which I don't understand.
The function that appears to be throwing the error works when used as a standalone function.

![image](https://user-images.githubusercontent.com/27255695/41364267-34278b3e-6f04-11e8-8808-da71647b7520.png)
![image](https://user-images.githubusercontent.com/27255695/41364328-5b8b6aba-6f04-11e8-9ddf-56f659ea0ed0.png)

**Comment by juanchon998** [comment]
@fletchapin @ethan92429

**Comment by ethan92429** [comment]
Heyo! Just now checking on this status. 

@fletchapin I can't push this to pip until all the tests pass on Travis. You can see the results [here](https://travis-ci.org/AguaClara/aide_design/jobs/388830202). I also get 10 failures on my local computer. As soon as you change either the tests or the code (whichever is correct) so that all the tests pass, and you push to master then tag the release, travis will automatically update pip. So to clarify, updating the pip aide_design packages requires:
* all the tests pass when pytest is run (the travis testing needs to pass)
* the code is merged into master
* the commit in master is tagged. 
Let me know if you need any help with this.

**Comment by fletchapin** [comment]
@ethan92429 @juanchon998 I've been busy for the last week working on fixing up houses my dad rents out, but I'll be done after tomorrow and can take a look at the test cases then.

If I run into any problems I'll let you know Ethan.

**Comment by fletchapin** [comment]
@ethan92429 I've been looking at the test cases that are failing and the code looks correct to me but the numbers don't match the expected values. I'm not sure when or how this change happened from when they were passing the test cases before.

**Comment by juanchon998** [comment]
I'm not sure if this will clarify, but we (me and the aide team) got all of the test cases to work on the filter_design branch. This morning there was an 'issue' with the version of numpy being used affecting how many functions passed the pytest, but we fixed that issue. Every function in lfom.py should pass a pytest if you have the latest version of numpy installed. 

I'm not sure if you want to merge filter_design into master now or wait until more files pass their pytests, but that is that status of lfom.py.

**Comment by oliver-leung** [comment]
More info on that version issue in #86

**Comment by ethan92429** [comment]
boof, this is still not resolved. I think what needs to happen is: I need to do a thorough analysis of aide_design before it gets updated. I think having aide_render and aide_design as two separate packages makes sense. Or at least two separate packages within the aide package. It has proved very difficult to keep track of so many different repos/packages. I'm not sure what has happened with the tests. The first step is to lock down the dependencies and make sure we have a well defined environment to work within.

**Comment by eak24** [comment]
Irrelevant to new system. We're changing files around a lot here.
